### ISSUE TITLE
[HowTo] get inlay hints working with neovim

### ISSUE THREAD

**Issue by dhruvinsh** [jbradaric/pyright-inlay-hints#2]
I was managed to get semantic highlight working with neovim.

But it seems that, I can not able to get the inlayHints working. I woundering what option should I be using here, from `coc-pyright` it is set via `pyright.inlayHints.functionReturnTypes`. Is that true here as well?

I tried, 
```lua
        pyright = { settings = { pyright = { inlayHints = { functionReturnTypes = true } } } },
```
but seems like I can not get the inlayhint working.

**Comment by jbradaric** [comment]
I'm not sure which neovim version you're using. On nightly, as far as I know inlay hints are disabled by default. To enable them for a buffer, execute `lua vim.lsp.inlay_hint.enable(0)`.
